# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1500, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1500, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1500, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1501, 1252))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_bldcConf = QtWidgets.QWidget()
        self.tab_bldcConf.setObjectName("tab_bldcConf")
        self.graphWidget = PlotWidget(self.tab_bldcConf)
        self.graphWidget.setGeometry(QtCore.QRect(140, 0, 1351, 541))
        self.graphWidget.setObjectName("graphWidget")
        self.pb_start = QtWidgets.QPushButton(self.tab_bldcConf)
        self.pb_start.setEnabled(False)
        self.pb_start.setGeometry(QtCore.QRect(710, 670, 161, 51))
        self.pb_start.setObjectName("pb_start")
        self.pb_resetMotor = QtWidgets.QPushButton(self.tab_bldcConf)
        self.pb_resetMotor.setGeometry(QtCore.QRect(890, 670, 81, 51))
        self.pb_resetMotor.setObjectName("pb_resetMotor")
        self.cb_controlType = QtWidgets.QComboBox(self.tab_bldcConf)
        self.cb_controlType.setGeometry(QtCore.QRect(10, 570, 99, 30))
        self.cb_controlType.setMinimumSize(QtCore.QSize(70, 30))
        self.cb_controlType.setObjectName("cb_controlType")
        self.cb_controlType.addItem("")
        self.cb_controlType.addItem("")
        self.cb_controlType.addItem("")
        self.lb_boardStatus = QtWidgets.QLabel(self.tab_bldcConf)
        self.lb_boardStatus.setGeometry(QtCore.QRect(710, 730, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_boardStatus.setFont(font)
        self.lb_boardStatus.setObjectName("lb_boardStatus")
        self.layoutWidget = QtWidgets.QWidget(self.tab_bldcConf)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 240, 102, 226))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.chb_currentIq = QtWidgets.QCheckBox(self.layoutWidget)
        self.chb_currentIq.setObjectName("chb_currentIq")
        self.verticalLayout_19.addWidget(self.chb_currentIq)
        self.chb_currentId = QtWidgets.QCheckBox(self.layoutWidget)
        self.chb_currentId.setObjectName("chb_currentId")
        self.verticalLayout_19.addWidget(self.chb_currentId)
        self.chb_desiredIq = QtWidgets.QCheckBox(self.layoutWidget)
        self.chb_desiredIq.setObjectName("chb_desiredIq")
        self.verticalLayout_19.addWidget(self.chb_desiredIq)
        self.chb_currentIab = QtWidgets.QCheckBox(self.layoutWidget)
        self.chb_currentIab.setObjectName("chb_currentIab")
        self.verticalLayout_19.addWidget(self.chb_currentIab)
        self.chb_currentUdq = QtWidgets.QCheckBox(self.layoutWidget)
        self.chb_currentUdq.setObjectName("chb_currentUdq")
        self.verticalLayout_19.addWidget(self.chb_currentUdq)
        self.chb_currentUab = QtWidgets.QCheckBox(self.layoutWidget)
        self.chb_currentUab.setObjectName("chb_currentUab")
        self.verticalLayout_19.addWidget(self.chb_currentUab)
        self.chb_currentPos = QtWidgets.QCheckBox(self.layoutWidget)
        self.chb_currentPos.setObjectName("chb_currentPos")
        self.verticalLayout_19.addWidget(self.chb_currentPos)
        self.chb_desiredPos = QtWidgets.QCheckBox(self.layoutWidget)
        self.chb_desiredPos.setObjectName("chb_desiredPos")
        self.verticalLayout_19.addWidget(self.chb_desiredPos)
        self.chb_currentSpeed = QtWidgets.QCheckBox(self.layoutWidget)
        self.chb_currentSpeed.setObjectName("chb_currentSpeed")
        self.verticalLayout_19.addWidget(self.chb_currentSpeed)
        self.chb_desiredSpeed = QtWidgets.QCheckBox(self.layoutWidget)
        self.chb_desiredSpeed.setObjectName("chb_desiredSpeed")
        self.verticalLayout_19.addWidget(self.chb_desiredSpeed)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_bldcConf)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 10, 121, 103))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_searchPort = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_searchPort.setObjectName("pb_searchPort")
        self.verticalLayout.addWidget(self.pb_searchPort)
        self.pb_connect = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_connect.setEnabled(False)
        self.pb_connect.setObjectName("pb_connect")
        self.verticalLayout.addWidget(self.pb_connect)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cb_ports = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_ports.setObjectName("cb_ports")
        self.verticalLayout_2.addWidget(self.cb_ports)
        self.lb_status = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_status.setObjectName("lb_status")
        self.verticalLayout_2.addWidget(self.lb_status)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_bldcConf)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 120, 98, 111))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.chb_rawdata = QtWidgets.QCheckBox(self.layoutWidget2)
        self.chb_rawdata.setObjectName("chb_rawdata")
        self.verticalLayout_4.addWidget(self.chb_rawdata)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chb_iacurr = QtWidgets.QCheckBox(self.layoutWidget2)
        self.chb_iacurr.setObjectName("chb_iacurr")
        self.verticalLayout_3.addWidget(self.chb_iacurr)
        self.chb_ibcurr = QtWidgets.QCheckBox(self.layoutWidget2)
        self.chb_ibcurr.setObjectName("chb_ibcurr")
        self.verticalLayout_3.addWidget(self.chb_ibcurr)
        self.chb_iccurr = QtWidgets.QCheckBox(self.layoutWidget2)
        self.chb_iccurr.setObjectName("chb_iccurr")
        self.verticalLayout_3.addWidget(self.chb_iccurr)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_bldcConf)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 470, 101, 71))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_20.addWidget(self.label_18)
        self.le_plotPoints = QtWidgets.QLineEdit(self.layoutWidget3)
        self.le_plotPoints.setObjectName("le_plotPoints")
        self.verticalLayout_20.addWidget(self.le_plotPoints)
        self.verticalLayout_21.addLayout(self.verticalLayout_20)
        self.pb_clearData = QtWidgets.QPushButton(self.layoutWidget3)
        self.pb_clearData.setObjectName("pb_clearData")
        self.verticalLayout_21.addWidget(self.pb_clearData)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_bldcConf)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 610, 158, 42))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pb_readConf = QtWidgets.QPushButton(self.layoutWidget4)
        self.pb_readConf.setMinimumSize(QtCore.QSize(60, 40))
        self.pb_readConf.setObjectName("pb_readConf")
        self.horizontalLayout_6.addWidget(self.pb_readConf)
        self.pb_writeConf = QtWidgets.QPushButton(self.layoutWidget4)
        self.pb_writeConf.setMinimumSize(QtCore.QSize(60, 40))
        self.pb_writeConf.setObjectName("pb_writeConf")
        self.horizontalLayout_6.addWidget(self.pb_writeConf)
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_bldcConf)
        self.layoutWidget_2.setGeometry(QtCore.QRect(190, 650, 161, 97))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_11.addWidget(self.label_9)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.sb_currQkP = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.sb_currQkP.setMaximum(65535)
        self.sb_currQkP.setObjectName("sb_currQkP")
        self.verticalLayout_12.addWidget(self.sb_currQkP)
        self.sb_currQkI = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.sb_currQkI.setMaximum(65535)
        self.sb_currQkI.setObjectName("sb_currQkI")
        self.verticalLayout_12.addWidget(self.sb_currQkI)
        self.sb_currQkD = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.sb_currQkD.setMaximum(65535)
        self.sb_currQkD.setObjectName("sb_currQkD")
        self.verticalLayout_12.addWidget(self.sb_currQkD)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_12)
        self.verticalLayout_10.addLayout(self.formLayout_2)
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_bldcConf)
        self.layoutWidget_3.setGeometry(QtCore.QRect(360, 650, 161, 97))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_14.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_14.addWidget(self.label_13)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.sb_speedkP = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.sb_speedkP.setMaximum(65535)
        self.sb_speedkP.setObjectName("sb_speedkP")
        self.verticalLayout_15.addWidget(self.sb_speedkP)
        self.sb_speedkI = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.sb_speedkI.setMaximum(65535)
        self.sb_speedkI.setObjectName("sb_speedkI")
        self.verticalLayout_15.addWidget(self.sb_speedkI)
        self.sb_speedkD = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.sb_speedkD.setMaximum(65535)
        self.sb_speedkD.setObjectName("sb_speedkD")
        self.verticalLayout_15.addWidget(self.sb_speedkD)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_15)
        self.verticalLayout_13.addLayout(self.formLayout_3)
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_bldcConf)
        self.layoutWidget_4.setGeometry(QtCore.QRect(540, 650, 161, 97))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_16.addWidget(self.label_14)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_17.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_17.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_17.addWidget(self.label_17)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.sb_poskP = QtWidgets.QSpinBox(self.layoutWidget_4)
        self.sb_poskP.setMaximum(65535)
        self.sb_poskP.setObjectName("sb_poskP")
        self.verticalLayout_18.addWidget(self.sb_poskP)
        self.sb_poskI = QtWidgets.QSpinBox(self.layoutWidget_4)
        self.sb_poskI.setMaximum(65535)
        self.sb_poskI.setObjectName("sb_poskI")
        self.verticalLayout_18.addWidget(self.sb_poskI)
        self.sb_poskD = QtWidgets.QSpinBox(self.layoutWidget_4)
        self.sb_poskD.setMaximum(65535)
        self.sb_poskD.setObjectName("sb_poskD")
        self.verticalLayout_18.addWidget(self.sb_poskD)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_18)
        self.verticalLayout_16.addLayout(self.formLayout_4)
        self.pb_runMotor = QtWidgets.QPushButton(self.tab_bldcConf)
        self.pb_runMotor.setEnabled(False)
        self.pb_runMotor.setGeometry(QtCore.QRect(1000, 670, 81, 51))
        self.pb_runMotor.setObjectName("pb_runMotor")
        self.cb_sendData = QtWidgets.QCheckBox(self.tab_bldcConf)
        self.cb_sendData.setGeometry(QtCore.QRect(120, 560, 70, 17))
        self.cb_sendData.setObjectName("cb_sendData")
        self.pb_saveData = QtWidgets.QPushButton(self.tab_bldcConf)
        self.pb_saveData.setGeometry(QtCore.QRect(10, 540, 101, 23))
        self.pb_saveData.setObjectName("pb_saveData")
        self.widget = QtWidgets.QWidget(self.tab_bldcConf)
        self.widget.setGeometry(QtCore.QRect(11, 651, 161, 97))
        self.widget.setObjectName("widget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.sb_currDkP = QtWidgets.QSpinBox(self.widget)
        self.sb_currDkP.setMaximum(65535)
        self.sb_currDkP.setObjectName("sb_currDkP")
        self.verticalLayout_7.addWidget(self.sb_currDkP)
        self.sb_currDkI = QtWidgets.QSpinBox(self.widget)
        self.sb_currDkI.setMaximum(65535)
        self.sb_currDkI.setObjectName("sb_currDkI")
        self.verticalLayout_7.addWidget(self.sb_currDkI)
        self.sb_currDkD = QtWidgets.QSpinBox(self.widget)
        self.sb_currDkD.setMaximum(65535)
        self.sb_currDkD.setObjectName("sb_currDkD")
        self.verticalLayout_7.addWidget(self.sb_currDkD)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.formLayout)
        self.widget1 = QtWidgets.QWidget(self.tab_bldcConf)
        self.widget1.setGeometry(QtCore.QRect(190, 560, 1081, 84))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_22 = QtWidgets.QLabel(self.widget1)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_23.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.widget1)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_23.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.widget1)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_23.addWidget(self.label_24)
        self.horizontalLayout_2.addLayout(self.verticalLayout_23)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.hs_speedVal = QtWidgets.QSlider(self.widget1)
        self.hs_speedVal.setEnabled(False)
        self.hs_speedVal.setMaximum(1600)
        self.hs_speedVal.setOrientation(QtCore.Qt.Horizontal)
        self.hs_speedVal.setObjectName("hs_speedVal")
        self.verticalLayout_6.addWidget(self.hs_speedVal)
        self.hs_currQval = QtWidgets.QSlider(self.widget1)
        self.hs_currQval.setMaximum(65535)
        self.hs_currQval.setOrientation(QtCore.Qt.Horizontal)
        self.hs_currQval.setObjectName("hs_currQval")
        self.verticalLayout_6.addWidget(self.hs_currQval)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.widget1)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.verticalLayout_6.addWidget(self.horizontalSlider_3)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_19 = QtWidgets.QLabel(self.widget1)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_22.addWidget(self.label_19)
        self.sb_currQval = QtWidgets.QSpinBox(self.widget1)
        self.sb_currQval.setMaximum(65535)
        self.sb_currQval.setObjectName("sb_currQval")
        self.verticalLayout_22.addWidget(self.sb_currQval)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget1)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_22.addWidget(self.spinBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout_22)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_bldcConf, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionSave_Config = QtWidgets.QAction(MainWindow)
        self.actionSave_Config.setObjectName("actionSave_Config")
        self.actionLoad_config = QtWidgets.QAction(MainWindow)
        self.actionLoad_config.setObjectName("actionLoad_config")
        self.menuFile.addAction(self.actionSave_Config)
        self.menuFile.addAction(self.actionLoad_config)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.hs_speedVal.valueChanged['int'].connect(self.label_19.setNum)
        self.hs_currQval.valueChanged['int'].connect(self.sb_currQval.setValue)
        self.sb_currQval.valueChanged['int'].connect(self.hs_currQval.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_start.setText(_translate("MainWindow", "Start graph"))
        self.pb_resetMotor.setText(_translate("MainWindow", "Reset Motor"))
        self.cb_controlType.setItemText(0, _translate("MainWindow", "Current control"))
        self.cb_controlType.setItemText(1, _translate("MainWindow", "Speed control"))
        self.cb_controlType.setItemText(2, _translate("MainWindow", "Position control"))
        self.lb_boardStatus.setText(_translate("MainWindow", "Board offline"))
        self.chb_currentIq.setText(_translate("MainWindow", "Current Iq"))
        self.chb_currentId.setText(_translate("MainWindow", "Current Id"))
        self.chb_desiredIq.setText(_translate("MainWindow", "Desired Iq"))
        self.chb_currentIab.setText(_translate("MainWindow", "Current Iab"))
        self.chb_currentUdq.setText(_translate("MainWindow", "Current Udq"))
        self.chb_currentUab.setText(_translate("MainWindow", "Current Uab"))
        self.chb_currentPos.setText(_translate("MainWindow", "Current position"))
        self.chb_desiredPos.setText(_translate("MainWindow", "Desired position"))
        self.chb_currentSpeed.setText(_translate("MainWindow", "Current speed"))
        self.chb_desiredSpeed.setText(_translate("MainWindow", "Desired speed"))
        self.pb_searchPort.setText(_translate("MainWindow", "Search ports"))
        self.pb_connect.setText(_translate("MainWindow", "Connect"))
        self.lb_status.setText(_translate("MainWindow", "Disconnected"))
        self.label.setText(_translate("MainWindow", "Data to acquire"))
        self.chb_rawdata.setText(_translate("MainWindow", "Raw data"))
        self.chb_iacurr.setText(_translate("MainWindow", "Current Ia"))
        self.chb_ibcurr.setText(_translate("MainWindow", "Current Ib"))
        self.chb_iccurr.setText(_translate("MainWindow", "Current Ic"))
        self.label_18.setText(_translate("MainWindow", "Plot points"))
        self.le_plotPoints.setText(_translate("MainWindow", "2000"))
        self.pb_clearData.setText(_translate("MainWindow", "Clear Data"))
        self.pb_readConf.setText(_translate("MainWindow", "Read config"))
        self.pb_writeConf.setText(_translate("MainWindow", "Write config"))
        self.label_6.setText(_translate("MainWindow", "Current Q"))
        self.label_7.setText(_translate("MainWindow", "KP"))
        self.label_8.setText(_translate("MainWindow", "KI"))
        self.label_9.setText(_translate("MainWindow", "KD"))
        self.label_10.setText(_translate("MainWindow", "Speed"))
        self.label_11.setText(_translate("MainWindow", "KP"))
        self.label_12.setText(_translate("MainWindow", "KI"))
        self.label_13.setText(_translate("MainWindow", "KD"))
        self.label_14.setText(_translate("MainWindow", "Position"))
        self.label_15.setText(_translate("MainWindow", "KP"))
        self.label_16.setText(_translate("MainWindow", "KI"))
        self.label_17.setText(_translate("MainWindow", "KD"))
        self.pb_runMotor.setText(_translate("MainWindow", "Run Motor"))
        self.cb_sendData.setText(_translate("MainWindow", "Send data"))
        self.pb_saveData.setText(_translate("MainWindow", "Save data"))
        self.label_2.setText(_translate("MainWindow", "Current D"))
        self.label_3.setText(_translate("MainWindow", "KP"))
        self.label_4.setText(_translate("MainWindow", "KI"))
        self.label_5.setText(_translate("MainWindow", "KD"))
        self.label_22.setText(_translate("MainWindow", "Speed"))
        self.label_23.setText(_translate("MainWindow", "Curr Q"))
        self.label_24.setText(_translate("MainWindow", "Speed"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bldcConf), _translate("MainWindow", "Debug tab"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave_Config.setText(_translate("MainWindow", "Save Config"))
        self.actionLoad_config.setText(_translate("MainWindow", "Load config"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
